export default [
    {
        DesignID: 'D001',
        DesignName: 'Elegant Flourish',
        EmbroideryType: '3D Puff Embroidery',
        Placement: 'Right Chest',
        PlacementCode: 'RC-001',
        ThreadColor1Name: 'Royal Blue',
        ThreadColor1Code: 'T100',
        ThreadColor2Name: 'Silver',
        ThreadColor2Code: 'T200',
        StitchCount: 15876,
        FabricType: 'Polyester',
        SmallSize: true,
        MediumSize: true,
        LargeSize: false,
        ExtraLargeSize: false,
        IsPersonalized: true,
        MaxCharactersPerLine: 12,
        NumberOfLines: 1,
        FontStyle: 'Script',
        ProductionTimeDays: 5
    },
    {
        DesignID: 'D002',
        DesignName: 'Modern Monogram',
        EmbroideryType: 'Flat Stitch',
        Placement: 'Left Sleeve',
        PlacementCode: 'LS-002',
        ThreadColor1Name: 'Black',
        ThreadColor1Code: 'T001',
        ThreadColor2Name: 'Gold',
        ThreadColor2Code: 'T250',
        StitchCount: 9400,
        FabricType: 'Cotton Blend',
        SmallSize: false,
        MediumSize: true,
        LargeSize: true,
        ExtraLargeSize: true,
        IsPersonalized: false,
        MaxCharactersPerLine: 0,
        NumberOfLines: 0,
        FontStyle: '',
        ProductionTimeDays: 3
    }
];
